name: End-to-End Test

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Backend to test"
        required: false
        type: choice
        default: "combined"
        options:
          - combined
          - discord
          - slack
          - symphony


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions-ext/python/setup@main
      with:
        version: "3.11"

    - name: Install
      run: uv pip install -e .[develop]

    - name: Run E2E Tests
      env:
        # Slack credentials
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        SLACK_TEST_CHANNEL_NAME: ${{ secrets.SLACK_TEST_CHANNEL_NAME }}
        SLACK_TEST_USER_NAME: ${{ secrets.SLACK_TEST_USER_NAME }}
        # Discord credentials
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_GUILD_NAME: ${{ secrets.DISCORD_GUILD_NAME }}
        DISCORD_TEST_CHANNEL_NAME: ${{ secrets.DISCORD_TEST_CHANNEL_NAME }}
        DISCORD_TEST_USER_NAME: ${{ secrets.DISCORD_TEST_USER_NAME }}
        # Symphony credentials
        SYMPHONY_HOST: ${{ secrets.SYMPHONY_HOST }}
        SYMPHONY_BOT_USERNAME: ${{ secrets.SYMPHONY_BOT_USERNAME }}
        SYMPHONY_BOT_PRIVATE_KEY_CONTENT: ${{ secrets.SYMPHONY_BOT_PRIVATE_KEY_CONTENT }}
        SYMPHONY_TEST_ROOM_NAME: ${{ secrets.SYMPHONY_TEST_ROOM_NAME }}
        SYMPHONY_TEST_USER_NAME: ${{ secrets.SYMPHONY_TEST_USER_NAME }}
      run: python -m chatom.tests.${{ github.event.inputs.variant || 'combined' }}_e2e
